version: "3"
services:
  site:
    image: bretfisher/jekyll-serve
    command: bundle exec jekyll server --config _local.yml --host '0.0.0.0'
    volumes:
      - ./docs:/site
    ports:
      - 4000:4000
